project:
  type: book
  output-dir: docs

book:
  title: "Bài tập thực hành R"
  author: Duc Nguyen
  site-url: https://www.tuhocr.com/
  date: last-modified
  date-format: "[Cập nhật:] YYYY MMMM DD"
  # cover-image: cover.png
  favicon: favicon.png
  # comments:
  #   hypothesis:
  #     theme: clean
  chapters:
    - index.qmd
    - part: "Các lệnh R căn bản"  
      chapters:
        - cac-lenh-ve-vector.qmd
    
  sidebar:
    style: "docked"
    search: true
    title: "Bài tập thực hành R"
          
# bibliography: F:/VAULT12/GRAND/grand.bib
number-sections: true
format:
  html:
    toc: true
    toc-title: "Mục lục"
    toc-location: right
    theme: default
    number-sections: false
    page-layout: full
    grid:
      sidebar-width: 280px
  # pdf:
  #   documentclass: scrreprt
engine: knitr
knitr:
  opts_chunk:
    R.options:
      width: 200


