project:
  type: book
  output-dir: docs

book:
  title: "Bài tập R"
  author: Duc Nguyen
  site-url: https://www.tuhocr.com/
  date: last-modified
  date-format: "[Cập nhật:] YYYY MMMM DD"
  # cover-image: cover.png
  favicon: logo.png
  # comments:
  #   hypothesis:
  #     theme: clean
  chapters:
    - index.qmd
    - part: "[**Các lệnh R căn bản**]{style='color:blue'}" 
      chapters:
        - cac-lenh-ve-vector.qmd
        - cac-lenh-ve-data-frame.qmd
        - cac-lenh-sap-xep-du-lieu.qmd
        - cac-lenh-regular-expression.qmd
    - part: "[**Các lệnh if-else, for-loop**]{style='color:blue'}" 
      chapters:
        - cac-lenh-if-else-for-loop.qmd      
    - part: "[**Các lệnh vẽ đồ thị**]{style='color:blue'}" 
      chapters:
        - template-do-thi-base-r-phan-1.qmd
        - cac-lenh-ve-do-thi-scatterplot.qmd 
        - cac-lenh-ve-do-thi-barchart.qmd 
        - cach-ve-duong-confidence-interval.qmd
        - cach-ve-do-thi-hai-truc-tung.qmd
    - part: "[**Các lệnh thống kê**]{style='color:blue'}" 
      chapters:
        - cac-lenh-thong-ke-mo-ta.qmd 
        - package-table1-thong-ke-mo-ta.qmd
    - part: "[**Các lệnh về function**]{style='color:blue'}" 
      chapters:
        - cach-xem-source-va-edit-function.qmd
    - part: "[**Các lệnh format văn bản**]{style='color:blue'}" 
      chapters:
        - cach-format-file-excel.qmd
        
  sidebar:
    style: "docked"
    search: true
    title: "Bài tập R"
          
# bibliography: F:/VAULT12/GRAND/grand.bib
# number-sections: true
format:
  html:
    theme:
      #light: [default, style/custom.scss]
      light: default
      dark: superhero
    toc: true
    toc-title: "Mục lục"
    toc-location: right
    toc_depth: 6
    # toc-expanded: true
    toc-expanded: 6
    css: styles.css
    toc_float:
      collapsed: false
      smooth_scroll: false
    number-sections: false
    page-layout: full
    grid:
      sidebar-width: 270px
  # pdf:
  #   documentclass: scrreprt
engine: knitr
knitr:
  opts_chunk:
    R.options:
      width: 200
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      


