project:
  type: book
  output-dir: docs

book:
  title: "Bài tập R"
  author: Duc Nguyen
  site-url: https://www.tuhocr.com/
  date: last-modified
  date-format: "[Cập nhật:] YYYY MMMM DD"
  # cover-image: cover.png
  favicon: favicon.png
  # comments:
  #   hypothesis:
  #     theme: clean
  chapters:
    - index.qmd
    - part: "[**Các lệnh R căn bản**]{style='color:blue'}" 
      chapters:
        - cac-lenh-ve-vector.qmd
        - cac-lenh-sap-xep-du-lieu.qmd
    - part: "[**Các lệnh vẽ đồ thị**]{style='color:blue'}" 
      chapters:
        - cac-lenh-ve-do-thi-scatterplot.qmd 
        - cac-lenh-ve-do-thi-barchart.qmd  
    - part: "[**Các lệnh thống kê**]{style='color:blue'}" 
      chapters:
        - cac-lenh-thong-ke-mo-ta.qmd     
    
  sidebar:
    style: "docked"
    search: true
    title: "Bài tập R"
          
# bibliography: F:/VAULT12/GRAND/grand.bib
number-sections: true
format:
  html:
    theme:
      #light: [default, style/custom.scss]
      light: default
      dark: superhero
    toc: true
    toc-title: "Mục lục"
    toc-location: right
    number-sections: false
    page-layout: full
    grid:
      sidebar-width: 260px
  # pdf:
  #   documentclass: scrreprt
engine: knitr
knitr:
  opts_chunk:
    R.options:
      width: 200
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      


